// <auto-generated />
using G01_14_Minimal_EF_MTM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G01_14_Minimal_EF_MTM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250218165140_Iniziale")]
    partial class Iniziale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G01_14_Minimal_EF_MTM.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("G01_14_Minimal_EF_MTM.Models.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Prodottos");
                });

            modelBuilder.Entity("G01_14_Minimal_EF_MTM.Models.ProdottoCategoria", b =>
                {
                    b.Property<int>("ProdottoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("ProdottoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("ProdottoCategorias");
                });

            modelBuilder.Entity("G01_14_Minimal_EF_MTM.Models.ProdottoCategoria", b =>
                {
                    b.HasOne("G01_14_Minimal_EF_MTM.Models.Categoria", "CategoriaNav")
                        .WithMany("ProdottoCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G01_14_Minimal_EF_MTM.Models.Prodotto", "ProdottoNav")
                        .WithMany("ProdottoCategorias")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaNav");

                    b.Navigation("ProdottoNav");
                });

            modelBuilder.Entity("G01_14_Minimal_EF_MTM.Models.Categoria", b =>
                {
                    b.Navigation("ProdottoCategorias");
                });

            modelBuilder.Entity("G01_14_Minimal_EF_MTM.Models.Prodotto", b =>
                {
                    b.Navigation("ProdottoCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
